import numpy as np
arr= np.array([[1,2],[3,4]])
arr1= np.array([[1,2],[3,4]])
print("Addition is: \n",arr+arr1)
print("Multiplication is: \n",arr@arr1)
print("Multiplication is: \n",np.matmul(arr,arr1))
print(np.mean(arr))
print(np.std(arr))
print(np.sqrt(np.std(arr)))
print(np.var(arr))
print(np.min(arr))
print(np.max(arr))
print(np.argmin(arr))
print(np.argmax(arr))